### ISSUE TITLE
Export individual tracks

### ISSUE THREAD

**Issue by Sanqui** [ipatix/agbplay#1]
It would be wonderful if player had a feature to export each channel of the song to a separate wav file without mixing.  I would love to use this tool to make some oscilloscope videos, like [this](https://www.youtube.com/watch?v=uHabZXsJGpw), for GBA music.

**Comment by ipatix** [comment]
Mhm, that sounds like a very cool feature. I'll need to think about how to implement that because the code was never really written to support anything else than one stream output.
Actually, if I change things as needed it would probably solve my issue (at least partially) that I had with individual VU meters for each tracks which I didn't end up implementing.

**Comment by ipatix** [comment]
So, I've been thinking about a few things, and there is a few things to clarify:
- There is not really a think such as "channels". The channels the agbplay uses internally are dynamically allocated and deleted (except the GB channels which are static)
- I'd go for a solution that is track based (each track can play multiple notes at the same time)

However, There is still things left like reverb. This effect is usually applied on the master bus after mixing is done. I've thought about two solutions:
1) Apply reverb on each track-buffer individually. This is probably the easiest solution, but I don't think it's the prettiest way to do it since reverb usually only needs to be applied to the master bus (although processing is probably definitely fast enough).
2) Process each track to a seperate buffer like solution #1 but don't apply reverb. Exporting of the individual tracks is possible at that stage to different files. Then all tracks get mixed to a "master-bus" and reverb is applied then and exported to yet another file. This would mean that your oscilloscopes wouldn't contain reverb in their graphs (which might be desirable or not) but you'd still have reverb on the "master-bus" output which you could use for the actual audio to listen to.

What's your thoughts about that (hope I didn't get too technical)?

**Comment by Sanqui** [comment]
Tracks make more sense, that was just my poor terminology.

I'm a little concerned about each track playing multiple notes at once, but I'd go with it for now.

As for master bus effects like reverb, I'd probably prefer if they were applied to each track individually.  By the way, do those effects apply to the Game Boy channels as well?  I'd presume not.  

Feel free to get technical. Thanks for giving this so much thought!

**Comment by ipatix** [comment]
Yes, reverb is not applied on the CG channels as they are directly produced by hardware on the real Gameboy.

Okay, I think I have a few more ideas how I can implement things now. Don't expect things too soon, but I'll get to work ;)

**Comment by ipatix** [comment]
So, I now have a first working version of your requested feature. Individual tracks can now be exported using the "E" key. Rendering to one file per songs still works using the "R" key.
Also, I know added the controls to the Readme.

However, since reworking certain parts of the code I had the program crash once and I haven't found out yet why it that happens. Kind of annoying that it happens so rarely that I have't been able to reproduce it since :/

**Comment by Sanqui** [comment]
I tested it out, and it works fantastically.  Here's three songs I tried for you to check out (make sure to watch in 60fps!):

**[Kuru Kuru Kururin - Cave](https://www.youtube.com/watch?v=UYdHD1XFFaQ)**
A simpler song with only six tracks.  You can see the three Game Boy channels to the right.  Looks like the lead is Game Boy Ch3.  Cool triangles and sawtooths.  SidWiz (the visualization tool) has issues latching on to the synth in the first track, but that should be worked on soon.

**[Pokémon Ruby: Introduction, Route 123](https://www.youtube.com/watch?v=hY5JVkZxuv0)**
A pretty complex piece of eight tracks.  SidWiz doesn't currently support more than eight channels, which is part of why I chose this song.  This looks wonderful, and SidWiz even managed to latch onto some of the trumpets.  I like how the Game Boy squares were delegated for stereo harmonies.

**[Mega Man Battle Network: Running Through the Cyberworld](https://www.youtube.com/watch?v=e_EmOK7PL30)**
This was the first piece I tried.  Unfortunately, my suspicions were correct when I assumed that the fact that tracks can play chords will prove problematic.  With two notes being played at once, the middle channel is impossible to latch to.

I'm not sure how to solve that beyond simply splitting tracks when notes play on them simultaneously.  While I'd probably prefer if percussion channels were kept mixed, I could do that myself with ffmpeg when relevant.

Thank you for going out of your way to implement this feature!  What do you think?

**Comment by ipatix** [comment]
Looks pretty cool. Looking forward to see more videos!

For solving the chords problem, I'm not really convinced of any solution. One could possibly use a stream pool and dynamically allocate the channels to a free stream. However, that would mean that the same voice might change it's output stream on the fly, which is not gonna look good. Another way would be to have more output streams per track and somehow dynamically distribute along those. However, for both ways the problem would arrive that incase too many notes are playing (remember that notes have a release phase and they don't shut off immediately) you'd need to merge multiple notes onto one stream.
Sadly in this case the GBA sound engine works more MIDI like than classic tracker software does.
